# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    always_put_required_named_parameters_first: ignore
    invalid_annotation_target: ignore
    unused_field: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # 기본 권장 사항
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true

    # 코드 품질
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true

    # 성능 최적화
    # use_build_context_synchronously: true  # 과도한 경고로 인해 임시 비활성화
    sized_box_for_whitespace: true
    prefer_const_constructors_in_immutables: true

    # 가독성
    sort_child_properties_last: true
    sort_constructors_first: true
    always_put_required_named_parameters_first: true

    # 접근성
    use_colored_box: true

    # 에러 처리
    only_throw_errors: true

    # 보안
    avoid_web_libraries_in_flutter: true

    # 스타일
    require_trailing_commas: true

    # TODO 주석 허용
    todo: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
