name: dimiplan

publish_to: "none"

uses-material-design: true

version: 2.0.0+2

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  animated_text_kit: ^4.2.3
  color_shade: ^1.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.1.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  http_cookie_store: ^0.0.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  web: ^1.1.1
  xtyle: ^0.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
