name: dimiplan

publish_to: "none"

uses-material-design: true

version: 1.0.0+1

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  color_shade: ^1.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_sign_in: ^6.3.0
  http: ^1.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  xtyle: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
