name: dimiplan

publish_to: "none"

uses-material-design: true

version: 2.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  animated_text_kit: ^4.2.3
  color_shade: ^1.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.2.0
  google_sign_in: ^6.3.0
  gpt_markdown: ^1.1.0
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  web: ^1.1.1
  xtyle: ^0.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
