name: Build Web

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.31.0-0.1.pre

      - name : Build
        uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: ./

      - name: Archive Production artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/web
