name: Build and Deploy

on:
  push:
    branches: [main, dev]
    paths:
      - "lib/**"
      - "assets/**"
      - "web/**"
      - "pubspec.yaml"
      - ".github/workflows/build_and_deploy.yml"
  workflow_dispatch:

jobs:
  Format_and_build:
    name: Format and Build
    runs-on: self-hosted

    permissions:
      contents: write
      actions: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 웹 클라이언트 ID 패치 적용
      - name: Apply Web Client ID Patch
        run: |
          echo "${{ secrets.WEB_CLIENT_ID_PATCH_BASE64 }}" | base64 --decode > web_patch.patch

          git apply web_patch.patch

          echo "Applied web client ID patch"

      - name: Build
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            flutter build web --wasm --release --dart-define=DEV_BUILD=true
          else
            flutter build web --wasm --release
          fi

      - name: Deploy on Cloudflare Pages
        run: bunx wrangler pages deploy build/web --project-name='dimiplan-mobile'

