name: Code Quality and Formatting

on:
  push:
    branches: [main, dev]
    paths:
      - "lib/**"
      - "assets/**"
      - "web/**"
      - "pubspec.yaml"
      - ".github/workflows/build_and_deploy.yml"
  workflow_dispatch:

jobs:
  Format_and_build:
    name: Format and Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          cache-sdk: true
          cache: true

      - name: Dart Analysis and Format
        run: |
          flutter pub get
          dart analyze lib
          dart fix --apply
          dart format lib

      - name: Commit Back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Dart Fix and Format
          commit_options: "--no-verify --signoff"

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{yaml,md,yml,json,toml,lock.json,lock.toml}