name: Build and Release

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android & Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.32.0-0.2.pre
          cache-sdk: true
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android Artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS Artifacts
          path: |
            build/ios/iphoneos/Runner.app/
