name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.32.0-0.2.pre
          cache-sdk: true
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android Artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS Artifacts
          path: |
            build/ios/iphoneos/Runner.app/

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.32.0-0.2.pre
          cache-sdk: true
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Artifacts
          path: |
            build\windows\x64\runner\Release\

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: beta
          version: 3.32.0-0.2.pre
          cache-sdk: true
          cache: true

      - name: Install OS Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux Artifacts
          path: |
            build/linux/x64/release/bundle
